[package]
name = "minesweeper-rs"
version = "0.1.0"
authors = ["Robert Mikhayelyan <rob.mikh@outlook.com>"]
edition = "2018"

[dependencies]
windows = { git = "https://github.com/microsoft/windows-rs" }
bindings = { path = "bindings" }
rand = "0.8.3"

[features]
show-mines = []
